info:
  app:
    name: <%= baseName %>
    description: <%= serviceDescription %>
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

server:
  port: 8080