spring: <% if (databaseType == 'mongodb') { %>
  data:
    mongodb:
      host: localhost
      port: 27017
      database: <%= baseName %> <% } %> <% if (databaseType == 'sql') { %>
  datasource:
    dataSourceClassName: <% if (devDatabaseType == 'mysql') { %>com.mysql.jdbc.jdbc2.optional.MysqlDataSource<% } else if (devDatabaseType == 'postgresql') { %>org.postgresql.ds.PGSimpleDataSource<% } else { %>org.h2.jdbcx.JdbcDataSource<% } %>
    url: <% if (devDatabaseType == 'mysql') { %>jdbc:mysql://localhost:3306/<%= baseName %><% } else if (devDatabaseType == 'postgresql') { %><% } else { %>jdbc:h2:mem:jhipster;DB_CLOSE_DELAY=-1<% } %>
    databaseName: <% if (devDatabaseType == 'postgresql') { %><%= baseName %><% } %>
    serverName: <% if (devDatabaseType == 'postgresql') { %>localhost<% } %>
    username: <% if (devDatabaseType == 'mysql') { %>root<% } else if (devDatabaseType == 'postgresql') { %><%= baseName %><% } %>
    password: <% if (devDatabaseType == 'mysql') { %>
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true<% } %><% } %>

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/